tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up

ports:
  - port: 3000
    onOpen: open-browser
  - port: 1880
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
