version: "3.7"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=ax.rudin@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--serverstransport.insecureskipverify=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - front
    restart: always
    networks:
      - tibotnet

  node-red-core:
    container_name: node-red-core
    build:
      context: .
      dockerfile: ./nodered-core.Dockerfile
    env_file: .env
    ports:
      - "1880:1880"
    networks:
      - tibotnet
    depends_on:
      - redis
    volumes:
      - ./node-red-core:/data 
      - ./nr-logs:/usr/src/node-red/logs
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-red-core.rule=Host(`api.ti-robots.ru`)"
      - "traefik.http.routers.node-red-core.entrypoints=websecure"
      - "traefik.http.routers.node-red-core.tls.certresolver=myresolver"
      - "traefik.http.services.node-red-core.loadBalancer.server.port=1880"

  node-red2:
    container_name: node-red2
    build:
      context: .
      dockerfile: ./nodered2.Dockerfile
    env_file: .env
    ports:
      - "1881:1881"
    networks:
      - tibotnet
    depends_on:
      - redis
    volumes:
      - ./node-red-data2:/data 
      - ./nr-logs:/usr/src/node-red/logs
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-red2.rule=Host(`worker1.ti-robots.ru`)"
      - "traefik.http.routers.node-red2.entrypoints=websecure"
      - "traefik.http.routers.node-red2.tls.certresolver=myresolver"
      - "traefik.http.services.node-red2.loadBalancer.server.port=1881"

  node-red-worker2:
    container_name: node-red-worker2
    build:
      context: .
      dockerfile: ./nodered-worker2.Dockerfile
    env_file: .env
    ports:
      - "1882:1882"
    networks:
      - tibotnet
    depends_on:
      - redis
    volumes:
      - ./node-red-worker2-data:/data 
      - ./nr-logs:/usr/src/node-red/logs
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-red2.rule=Host(`worker2.ti-robots.ru`)"
      - "traefik.http.routers.node-red2.entrypoints=websecure"
      - "traefik.http.routers.node-red2.tls.certresolver=myresolver"
      - "traefik.http.services.node-red2.loadBalancer.server.port=1882"

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass YzRAdGgkFg
    ports:
     - "6379:6379"
    environment:
         - REDIS_REPLICATION_MODE=master
    volumes:
      - ./redis-data:/data
    restart: always
    networks:
      - tibotnet

  priceserver:
    container_name: priceserver
    build:
      context: ./priceserver
      dockerfile: ./Dockerfile.dev
    env_file: .env
    volumes:
      - './priceserver/:/usr/src/app'
    restart: on-failure
    depends_on:
      - redis
    networks:
      - tibotnet

  telegrambot:
    container_name: telegrambot
    build:
      context: ./telegrambot
      dockerfile: ./Dockerfile.dev
    env_file: .env
    volumes:
      - './telegrambot/:/usr/src/app'
    restart: on-failure
    depends_on:
      - redis
    networks:
      - tibotnet
  
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: ./Dockerfile.dev
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - './front/:/usr/src/app'
    restart: always
    depends_on:
      - redis
      - node-red-core
      - node-red-worker2

    networks:
      - tibotnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`tir4dev.ti-robots.ru`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=myresolver"
      - "traefik.http.services.front.loadBalancer.server.port=3000"
      - "traefik.http.middlewares.cors.headers.customResponseHeaders.Access-Control-Allow-Origin=https://tir4dev.ti-robots.ru"
      - "traefik.http.routers.front.middlewares=cors"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=300"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"

volumes:
  redis-data:
  node-red-core:
  node-red-data2:
  node-red-worker2-data:

networks:
  tibotnet: